---
services: docker
language: python
install:
  - pip3 install docker "molecule<3.0" openshift jmespath
  - curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-$(uname)-amd64 && chmod +x kind && sudo mv kind /usr/local/bin
  - curl -Lo ./kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
script:
  - kind create cluster
  - kind get kubeconfig > ~/.kube/config
  - ./test.sh
